name: Capitalize Input

on: [push]

jobs:
  capitalize:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Capitalize Input
        run: echo "${{ github.event.inputs.input_string }}" | tr '[:lower:]' '[:upper:]'
        shell: bash
      
      - name: Display Capitalized Input
        run: echo "Capitalized input:${{ steps.capitalize_input.outputs.capitalized_input }}"
